global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'user@prestashop.local'
        from: 'alertmanager@prestashop.local'
        smarthost: 'mailhog:1025'
        require_tls: false
        send_resolved: true