services:
  prestashop:
    build: .
    container_name: prestashop
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      DB_SERVER: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_USER: ${DB_USER:-prestashop}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      PS_DOMAIN: ${PS_DOMAIN:-localhost}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL:-1}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-dashboard}
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
      PS_LANGUAGE: ${PS_LANGUAGE:-en}

    networks:
      - prestashop_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - prestashop_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - prestashop
    networks:
      - prestashop_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    networks:
      - prestashop_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - prestashop_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - prestashop_network

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - prestashop_network

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - prestashop_network

  backup:
    image: mysql:5.7
    volumes:
      - ./backup.sh:/backup.sh
      - backup_data:/backups
    command: bash -c "chmod +x /backup.sh && /backup.sh"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - prestashop_network
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - prestashop_network

volumes:
  prestashop_data:
  db_data:
  grafana_data:
  backup_data:

networks:
  prestashop_network:
    driver: bridge
